"""
Simple PDF Generator Test - Run this separately
"""

import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

# Create reports folder
os.makedirs("reports", exist_ok=True)

# Create PDF
doc = SimpleDocTemplate("reports/report.pdf", pagesize=letter)
styles = getSampleStyleSheet()

story = []
story.append(Paragraph("CryptoSteg - Encode Report", styles['Heading1']))
story.append(Spacer(1, 20))
story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
story.append(Spacer(1, 10))
story.append(Paragraph("<b>Input Image:</b> cat.png", styles['Normal']))
story.append(Paragraph("<b>Output Image:</b> stego_image.png", styles['Normal']))
story.append(Paragraph("<b>Message Length:</b> 48 characters", styles['Normal']))
story.append(Paragraph("<b>Bytes Hidden:</b> 48 bytes", styles['Normal']))
story.append(Paragraph("<b>Encryption:</b> AES-256-CBC", styles['Normal']))
story.append(Spacer(1, 30))
story.append(Paragraph("Generated by CryptoSteg v3.0 | AES-256 + LSB Steganography", styles['Normal']))

doc.build(story)

print("=" * 50)
print("✅ PDF CREATED SUCCESSFULLY!")
print(f"📁 Location: {os.path.abspath('reports/report.pdf')}")
print("=" * 50)